name: IvanBlatter
favicon: null
layout_spectrum: 0.5058924232143909
typography_spectrum: 0.19415918597951531
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8957586952019483
  lightness: 0.12957674427889287
  saturation: 0.7430884644854814
  rhythmicContrast: 0.47892200481146574
purpose: []
